#!/usr/bin/env bash
# Mainnet environment — DORMANT (genesis ceremony required before use)
# After ceremony: source /root/kovanica-workspace/mainnet/env.sh
# Runs: kovanica-node explorer 127.0.0.1:8080

# Consensus: PoA for bootstrap (T+0 to T+14d), then PoW
# See GENESIS_PLAYBOOK.md Phase 3-4

# Authority set — generated by AUTHORITY_KEY_CEREMONY.md ceremony
# 7 genesis signers (5-of-7) + 7 validators (5-of-7) = separate sets
# Replace with ceremony outputs:
export KOVANICA_CONSENSUS=poa
export KOVANICA_AUTHORITIES=<VALIDATOR_PUBKEY_1>,<VALIDATOR_PUBKEY_2>,<VALIDATOR_PUBKEY_3>,<VALIDATOR_PUBKEY_4>,<VALIDATOR_PUBKEY_5>,<VALIDATOR_PUBKEY_6>,<VALIDATOR_PUBKEY_7>
export KOVANICA_AUTHORITY_THRESHOLD=5
export KOVANICA_SLOT_DURATION=120000  # 120 seconds (mainnet)

# Node config
export KOVANICA_LISTEN=0.0.0.0:9000
export KOVANICA_PEERS=seed1.mainnet.kovanica.online:9000,seed2.mainnet.kovanica.online:9000,seed3.mainnet.kovanica.online:9000
export KOVANICA_FAUCET=0
export KOVANICA_ALLOW_RESET=0
export KOVANICA_OPERATOR=0
export KOVANICA_DATA=/var/lib/kovanica-mainnet

# Block production (validator only)
# export KOVANICA_PRODUCE=1
# export KOVANICA_PRODUCE_SECS=120
# Authority key loaded from secure file:
# source /etc/kovanica/authority-keys/authority-N.env

# Mainnet constants (RFC-006 canonical)
export KOVANICA_MAX_SUPPLY=9020000000000000    # 90.2M KVNC in atoms
export KOVANICA_SUBSIDY=1000000000             # 10 KVNC genesis subsidy
export KOVANICA_ERA_BLOCKS=2000000             # 2M blocks per era
export KOVANICA_DECAY_NUM=3                    # α = 3/4
export KOVANICA_DECAY_DEN=4
export KOVANICA_MATURITY=100                   # 100-block coinbase maturity
export KOVANICA_FEE_BURN_NUM=3                 # 75% burn
export KOVANICA_FEE_BURN_DEN=4